import { prisma } from "@/lib/prisma";
import bcrypt from "bcryptjs";
import { z } from "zod";

const ALPHABET = process.env.SHARE_CODE_ALPHABET;
const DEFAULT_LENGTH = Number(process.env.SHARE_CODE_LENGTH);
//ownerId tạm thời để test
const TEST_OWNER_ID = "cmm5uppvt0000wkvpsuzmfn16"; // ⚠️ id phải tồn tại trong DB
//Gen Code để tạo link share
function genCode(len = DEFAULT_LENGTH) {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let out = "";
  for (let i = 0; i < len; i++)
    out += ALPHABET[Math.floor(Math.random() * chars.length)];
  return out;
}

const CreateSharePageSchema = z.object({
  appId: z.string().min(1),
  note: z.string().max(2000).optional().nullable(),
  expiresAt: z.string().datetime().optional().nullable(),
  code: z.string().max(64).optional().nullable(),
  passes: z
    .array(
      z.object({
        pass: z.string().min(1).max(128),
        quota: z.number().int().min(1),
        label: z.string().max(120).optional().nullable(),
      }),
    )
    .min(1),
});

// API lấy dữ liệu bảng
export async function GET() {
  try {
    const items = await prisma.sharePage.findMany({
      include: {
        app: {
          select: {
            id: true,
            name: true,
            slug: true,
            packageType: true,
          },
        },
        _count: {
          select: {
            passes: true,
          },
        },
      },
      orderBy: {
        createdAt: "desc",
      },
    });

    return Response.json({
      success: true,
      items,
    });
  } catch (err) {
    return Response.json(
      {
        success: false,
        message: "Failed to load share pages",
        detail: String(err?.message || err),
      },
      { status: 500 }
    );
  }
}


export async function POST(req) {
  try {
    const body = await req.json();
    const parsed = CreateSharePageSchema.safeParse(body);
    if (!parsed.success) {
      return Response.json(
        {
          success: false,
          message: "Validation failed",
          errors: parsed.error.flatten(),
        },
        { status: 400 },
      );
    }

    const { appId, note, expiresAt, code, passes } = parsed.data;

    // code: server-generated by default
    let finalCode = (code && code.trim()) || genCode(8);

    // ensure unique code (simple retry)
    for (let i = 0; i < 5; i++) {
      const exists = await prisma.sharePage.findUnique({
        where: { code: finalCode },
      });
      if (!exists) break;
      finalCode = genCode(8);
    }

    const sharePage = await prisma.$transaction(async (tx) => {
      const created = await tx.sharePage.create({
        data: {
          ownerId: TEST_OWNER_ID, // 👈 gán ở đây
          appId,
          code: finalCode,
          note: note ?? null,
          expiresAt: expiresAt ? new Date(expiresAt) : null,
        },
      });

      // hash passes
      const passRows = await Promise.all(
        passes.map(async (p) => {
          const passHash = await bcrypt.hash(p.pass, 10);
          return {
            sharePageId: created.id,
            passwordHash: passHash,
            label: p.label ?? null,
            quotaTotal: p.quota,
            // quotaRemaining: p.quota,
          };
        }),
      );

      await tx.sharePass.createMany({ data: passRows });

      return created;
    });

    const origin = req.headers.get("origin") || "";
    const url = origin ? `${origin}/${sharePage.code}` : `/${sharePage.code}`;

    return Response.json({
      success: true,
      sharePage: {
        ownerId: TEST_OWNER_ID, // gán ở đây
        id: sharePage.id,
        code: sharePage.code,
        appId: sharePage.appId,
        note: sharePage.note,
        expiresAt: sharePage.expiresAt,
      },
      url,
      passesCreated: passes.length,
    });
  } catch (err) {
    return Response.json(
      {
        success: false,
        message: "Server error",
        detail: String(err?.message || err),
      },
      { status: 500 },
    );
  }
}
